name: "3rd Party Libraries Install"
description: "3rd Party Libraries Install"

inputs:
  os:
    description: "operating system"
    required: true

runs:
  using: "composite"
  steps:
    - name: Install Libraries (Linux/macOS)
      shell: bash
      if: inputs.os == 'Linux' || inputs.os == 'macOS'
      run: |
        ./scripts/library_tool.sh capnp install --prefix="$SCALER_THIRDPARTY_PREFIX"
        ./scripts/library_tool.sh libuv install --prefix="$SCALER_THIRDPARTY_PREFIX"
        ./scripts/library_tool.sh openssl install --prefix="$SCALER_THIRDPARTY_PREFIX"

    - name: Install Libraries (Windows)
      shell: pwsh
      if: inputs.os == 'Windows'
      run: |
        ./scripts/library_tool.ps1 capnp install --prefix="$env:SCALER_THIRDPARTY_PREFIX"
        ./scripts/library_tool.ps1 libuv install --prefix="$env:SCALER_THIRDPARTY_PREFIX"
        ./scripts/library_tool.ps1 openssl install --prefix="$env:SCALER_THIRDPARTY_PREFIX"
